name: Build App

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      comment:
        description: Comment on triggering this workflow
        required: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Build Image with Server-Side Rendering & Push to Packages
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: seventv/app
          tag_with_ref: true
